---
strict: true
site_name: kaiba
site_description: Configurable json to json mapping
theme:
  name: material
  palette:
    scheme: slate
    primary: green
    accent: deep-orange
  icon:
    logo: material/language-python
  language: en
  features:
    - navigation.tabs
repo_name: kaiba-tech/kaiba
repo_url: https://github.com/kaiba-tech/kaiba
edit_uri: ""
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home:
      - Home: index.md
      - Usage: usage.md
      - Introduction: introduction.md
      - Configuration: configuration.md
      - Contributing: contributing.md
      - Changelog: changelog.md
  - Usecases:
      - Usecases: usecases/usecases.md
